### ISSUE TITLE
yahoo inbox issue

### ISSUE THREAD

**Issue by haseeb2k9** [sendpulse/sendpulse-rest-api-php#23]
i tried this for yahoo  , but email no receive in inbox . always in spam folder , is there any special setting for yahoo .

```
> /*
>  * Example: Send mail using SMTP
>  */
> $email = array(
>     'html' => '<p>Hello!</p>',
>     'text' => 'Hello!',
>     'subject' => 'Mail subject',
>     'from' => array(
>         'name' => 'John',
>         'email' => 'sender@example.com',
>     ),
>     'to' => array(
>         array(
>             'name' => 'Subscriber Name',
>             'email' => 'subscriber@example.com',
>         ),
>     ),
>     'bcc' => array(
>         array(
>             'name' => 'Manager',
>             'email' => 'manager@example.com',
>         ),
>     ),
>     'attachments' => array(
>         'file.txt' => file_get_contents(PATH_TO_ATTACH_FILE),
>     ),
> );
> var_dump($SPApiClient->smtpSendMail($email));
```

**Comment by sendpulse** [comment]
Hello, @haseeb2k9 

Thank you for your answer. Here following are some important strategies and spam filter testing tips to help you get into  inboxes and prevent deliverability problems in the future:
- Check the content of your emails. Do not use the word spam (spam filter words) in the subject line and body of the message ( e.g. Earn money and do not work!) and use personalization for your emails. If you have a deliverability issue, check to see if the content is to blame. Start by sending a neutral message to an email address using your existing sending infrastructure including the “from” address and sending domain. If it doesn’t get filtered to junk mail, break up the copy of the problem email and be sure to send it in pieces to determine if the problem is located in the subject line or message copy. And keep in mind that it could be an image or a link that’s causing the deliverability issue.
- Pay attention to the image in the newsletter, because most of mail services consider the mail with small amount of text as spam. An ideal ratio text/images approximately 80/20.
- Use the corporate address as sender, as a good tip, for this sender, you can set up your own SPF and DKIM records. They're 2 effective email signatures against spoofing, phishing or impersonation. When recipients receive your emails, their spam filters automatically poke your domain to see if those signatures are not forged. 
- Keep track of your engagement metrics. Are your subscribers opening and clicking your emails? Or do they skip and delete your emails without opening them, unsubscribe, or report them as spam? Email service providers use such engagement metrics to determine whether its users want your emails. So if your subscribers are inactive — i.e., if they haven’t opened or clicked your emails in a certain period of time, such as 6 months — you should consider running a reengagement campaign. In this way, you’ll identify the subscribers who aren’t interested in receiving your emails and can remove them from your list.
- Create an opt-in subscription process. Do not forget to add the subscription information into your email. In fact, email service providers recommend using a double opt-in subscription process, which involves sending a follow-up message that each subscriber needs to respond to.

Plus, we recommend to read Yahoo's best practices for bulk email, you can find them at the following link: https://help.yahoo.com/kb/SLN3435.html

Follow these recommendations and mailing should not come into spam.
If there are any questions feel free to ask.
